// Mocks generated by Mockito from annotations
// in rpg/test/mocks/core/services/navigation_service_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:flutter/material.dart' as _i1;
import 'package:mockito/mockito.dart' as _i2;
import 'package:rpg/core/services/navigation/source/navigation_service.dart' as _i3;
import 'package:rpg/layers/presentation/widgets/custom-button/custom_button.dart' as _i6;
import 'package:rpg/layers/presentation/widgets/custom-popup/custom_pop_up.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGlobalKey_0<T extends _i1.State<_i1.StatefulWidget>> extends _i2.SmartFake implements _i1.GlobalKey<T> {
  _FakeGlobalKey_0(Object parent, Invocation parentInvocation) : super(parent, parentInvocation);
}

/// A class which mocks [NavigationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNavigationService extends _i2.Mock implements _i3.NavigationService {
  MockNavigationService() {
    _i2.throwOnMissingStub(this);
  }

  @override
  _i1.GlobalKey<_i1.NavigatorState> get navigatorKey => (super.noSuchMethod(
    Invocation.getter(#navigatorKey),
    returnValue: _FakeGlobalKey_0<_i1.NavigatorState>(
      this,
      Invocation.getter(#navigatorKey),
    ),
  ) as _i1.GlobalKey<_i1.NavigatorState>);

  @override
  _i4.Future<T?>? push<T extends Object?>(
    _i1.Widget? page, {
    Object? arguments,
  }) => (super.noSuchMethod(
    Invocation.method(#push, [page], {#arguments: arguments}),
  ) as _i4.Future<T?>?);

  @override
  void pop<T extends Object?>([T? result]) => super.noSuchMethod(
    Invocation.method(#pop, [result]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<T?> pushReplacement<T extends Object?, TO extends Object?>(
    _i1.Widget? page, {
    Object? arguments,
    TO? result,
  }) => (super.noSuchMethod(
    Invocation.method(
      #pushReplacement,
      [page],
      {#arguments: arguments, #result: result},
    ),
    returnValue: _i4.Future<T?>.value(),
  ) as _i4.Future<T?>);

  @override
  _i4.Future<T?> pushAndRemoveUntil<T extends Object?>(
    _i1.Widget? page, {
    _i1.RoutePredicate? predicate,
    Object? arguments,
  }) => (super.noSuchMethod(
    Invocation.method(
      #pushAndRemoveUntil,
      [page],
      {#predicate: predicate, #arguments: arguments},
    ),
    returnValue: _i4.Future<T?>.value(),
  ) as _i4.Future<T?>);

  @override
  void popUntil(_i1.RoutePredicate? predicate) => super.noSuchMethod(
    Invocation.method(#popUntil, [predicate]),
    returnValueForMissingStub: null,
  );

  @override
  void popUntilFirst() => super.noSuchMethod(
    Invocation.method(#popUntilFirst, []),
    returnValueForMissingStub: null,
  );

  @override
  bool canPop() => (super.noSuchMethod(Invocation.method(#canPop, []), returnValue: false) as bool);

  @override
  void showSheet(
    _i1.Widget? sheet, {
    bool? isDismissible = true,
    _i5.VoidCallback? onDismiss,
  }) => super.noSuchMethod(
    Invocation.method(
      #showSheet,
      [sheet],
      {#isDismissible: isDismissible, #onDismiss: onDismiss},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void showFullScreenSheet(_i1.Widget? sheet, {bool? isDismissible = true}) => super.noSuchMethod(
    Invocation.method(
      #showFullScreenSheet,
      [sheet],
      {#isDismissible: isDismissible},
    ),
    returnValueForMissingStub: null,
  );

  @override
  void showErrorPopUp({
    required String? title,
    String? message,
    _i1.Widget? content,
    required String? buttonTitle,
    bool? willPop = false,
  }) => super.noSuchMethod(
    Invocation.method(#showErrorPopUp, [], {
      #title: title,
      #message: message,
      #content: content,
      #buttonTitle: buttonTitle,
      #willPop: willPop,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> showPopUp({
    required String? title,
    String? message,
    _i1.Widget? content,
    required List<_i6.CustomButton>? actions,
    _i5.Color? textColor,
    bool? isDismissible = true,
    _i7.ActionsDirection? actionsDirection = _i7.ActionsDirection.horizontal,
    String? icon,
    String? image,
  }) => (super.noSuchMethod(
    Invocation.method(#showPopUp, [], {
      #title: title,
      #message: message,
      #content: content,
      #actions: actions,
      #textColor: textColor,
      #isDismissible: isDismissible,
      #actionsDirection: actionsDirection,
      #icon: icon,
      #image: image,
    }),
    returnValue: _i4.Future<void>.value(),
    returnValueForMissingStub: _i4.Future<void>.value(),
  ) as _i4.Future<void>);

  @override
  void showSnackbar({required String? message, double? bottomMargin}) => super.noSuchMethod(
    Invocation.method(#showSnackbar, [], {
      #message: message,
      #bottomMargin: bottomMargin,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void showLoader() => super.noSuchMethod(
    Invocation.method(#showLoader, []),
    returnValueForMissingStub: null,
  );
}
