package com.apergas.rpg.android.presentation.forest.world

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

data class AtlasFrame(
    val name: String,
    val x: Int,
    val y: Int,
    val width: Int,
    val height: Int,
    val pivotX: Float,
    val pivotY: Float,
)

/** Reads the Phaser JSON-hash atlas generated by build_assets.py, pivots included. */
object AtlasParser {
    @Serializable private data class Rect(val x: Int, val y: Int, val w: Int, val h: Int)
    @Serializable private data class Pivot(val x: Float = 0.5f, val y: Float = 0.5f)
    @Serializable private data class Frame(val frame: Rect, val pivot: Pivot = Pivot())
    @Serializable private data class Atlas(val frames: Map<String, Frame>)

    private val json = Json { ignoreUnknownKeys = true }

    fun parse(text: String): Map<String, AtlasFrame> =
        json.decodeFromString<Atlas>(text).frames.mapValues { (name, entry) ->
            AtlasFrame(name, entry.frame.x, entry.frame.y, entry.frame.w, entry.frame.h, entry.pivot.x, entry.pivot.y)
        }
}
