// Mocks generated by Mockito from annotations
// in rpg/test/mocks/domain/repositories/repository_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'package:mockito/mockito.dart' as _i1;
import 'package:rpg/layers/domain/entities/game/game_session_entity.dart'
    as _i3;
import 'package:rpg/layers/domain/repositories/level/level_repository.dart'
    as _i4;
import 'package:rpg/layers/domain/repositories/session/game_session_repository.dart'
    as _i5;
import 'package:rpg/layers/domain/world/world.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWorld_0 extends _i1.SmartFake implements _i2.World {
  _FakeWorld_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGameSessionEntity_1 extends _i1.SmartFake
    implements _i3.GameSessionEntity {
  _FakeGameSessionEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LevelRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLevelRepository extends _i1.Mock implements _i4.LevelRepository {
  MockLevelRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.World load() => (super.noSuchMethod(
    Invocation.method(#load, []),
    returnValue: _FakeWorld_0(this, Invocation.method(#load, [])),
  ) as _i2.World);
}

/// A class which mocks [GameSessionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameSessionRepository extends _i1.Mock
    implements _i5.GameSessionRepository {
  MockGameSessionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.GameSessionEntity current() => (super.noSuchMethod(
    Invocation.method(#current, []),
    returnValue: _FakeGameSessionEntity_1(
      this,
      Invocation.method(#current, []),
    ),
  ) as _i3.GameSessionEntity);

  @override
  void save(_i3.GameSessionEntity? session) => super.noSuchMethod(
    Invocation.method(#save, [session]),
    returnValueForMissingStub: null,
  );
}
