import SpriteKit
import UIKit

struct AtlasFrame: Decodable {
    struct Rect: Decodable { let x: Int; let y: Int; let w: Int; let h: Int }
    struct Pivot: Decodable { let x: Double; let y: Double }
    let frame: Rect
    let pivot: Pivot?
}

/// LPC textures and the Phaser JSON-hash atlas generated by build_assets.py.
final class LpcAtlas {
    private struct AtlasFile: Decodable { let frames: [String: AtlasFrame] }

    private let forestImage: CGImage
    private let forestTexture: SKTexture
    private let alpha: [UInt8]
    let frames: [String: AtlasFrame]
    private(set) var textures: [String: SKTexture] = [:]

    init() {
        let url = Bundle.main.url(forResource: "forest", withExtension: "json", subdirectory: "lpc")!
        frames = try! JSONDecoder().decode(AtlasFile.self, from: Data(contentsOf: url)).frames
        forestImage = Self.image(named: "forest").cgImage!
        forestTexture = Self.texture(from: forestImage)
        alpha = Self.alphaChannel(of: forestImage)
        for (name, entry) in frames {
            textures[name] = Self.subTexture(of: forestTexture, image: forestImage, x: entry.frame.x, y: entry.frame.y, width: entry.frame.w, height: entry.frame.h)
        }
    }

    /// SpriteKit anchors from the bottom-left, the atlas pivot from the top-left.
    func anchor(of name: String) -> CGPoint {
        let pivot = frames[name]?.pivot
        return CGPoint(x: pivot?.x ?? 0.5, y: 1 - (pivot?.y ?? 0.5))
    }

    /// Same threshold as the web: the painted tree shadow does not count as the tree.
    func isOpaque(frame name: String, localX: Int, localY: Int) -> Bool {
        guard let entry = frames[name], (0..<entry.frame.w).contains(localX), (0..<entry.frame.h).contains(localY) else { return false }
        let index = (entry.frame.y + localY) * forestImage.width + entry.frame.x + localX
        return alpha[index] >= 200
    }

    static func image(named name: String) -> UIImage {
        UIImage(contentsOfFile: Bundle.main.path(forResource: name, ofType: "png", inDirectory: "lpc")!)!
    }

    static func texture(from image: CGImage) -> SKTexture {
        let texture = SKTexture(cgImage: image)
        texture.filteringMode = .nearest
        return texture
    }

    /// A cell of a sheet, given in top-left pixel coordinates.
    static func subTexture(of texture: SKTexture, image: CGImage, x: Int, y: Int, width: Int, height: Int) -> SKTexture {
        let imageWidth = Double(image.width), imageHeight = Double(image.height)
        let rect = CGRect(x: Double(x) / imageWidth, y: 1 - Double(y + height) / imageHeight, width: Double(width) / imageWidth, height: Double(height) / imageHeight)
        let cell = SKTexture(rect: rect, in: texture)
        cell.filteringMode = .nearest
        return cell
    }

    private static func alphaChannel(of image: CGImage) -> [UInt8] {
        var pixels = [UInt8](repeating: 0, count: image.width * image.height)
        let context = CGContext(data: &pixels, width: image.width, height: image.height, bitsPerComponent: 8, bytesPerRow: image.width, space: CGColorSpaceCreateDeviceGray(), bitmapInfo: CGImageAlphaInfo.alphaOnly.rawValue)!
        context.draw(image, in: CGRect(x: 0, y: 0, width: image.width, height: image.height))
        return pixels
    }
}
