// Mocks generated by Mockito from annotations
// in rpg/test/layers/data/repositories/level/level_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'package:mockito/mockito.dart' as _i1;
import 'package:rpg/layers/data/datasources/level/local/dbo/level_dbo.dart'
    as _i2;
import 'package:rpg/layers/data/datasources/level/source/level_local_datasource.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLevelDBO_0 extends _i1.SmartFake implements _i2.LevelDBO {
  _FakeLevelDBO_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LevelLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLevelLocalDatasource extends _i1.Mock
    implements _i3.LevelLocalDatasource {
  MockLevelLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LevelDBO fetch() => (super.noSuchMethod(
    Invocation.method(#fetch, []),
    returnValue: _FakeLevelDBO_0(this, Invocation.method(#fetch, [])),
  ) as _i2.LevelDBO);
}
